#!/usr/bin/env python3
"""Keep the repo index in sync with skills/ and scan for private info.

- Every skills/<name>/ needs a SKILL.md and an entry in skills.json (en + zh one-liners).
- Regenerates the skill table in README.md (between the AUTO markers) and .claude-plugin/marketplace.json.
- Requires a "## <name>" section in README.md for each skill (written by hand).
- Scans tracked/staged text files for things that must not be published.
Exit code 1 on any problem. Usage: python3 scripts/sync.py [--check]
"""
import json, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN, END = '<!-- SKILLS:BEGIN (auto-generated by scripts/sync.py) -->', '<!-- SKILLS:END -->'

# Generic patterns only; never put personal names in this file.
PRIVATE = [
    (r'/Users/[A-Za-z0-9._-]+', 'absolute home path'),
    (r'~/(Documents|Desktop|Downloads|Library)/', 'path under personal folders'),
    (r'[\w.+-]+@(?!example\.)[\w-]+\.(com|cn|net|org)\b', 'email address'),
    (r'\b(sk-[A-Za-z0-9]{16,}|ghp_[A-Za-z0-9]{20,}|github_pat_\w{20,}|AKIA[0-9A-Z]{12,})', 'API key / token'),
    (r'见记忆|用户的名字和署名', 'pointer to private memory'),
]
EXTRA = ROOT / '.privacy-terms'   # optional, git-ignored: one extra forbidden term per line (your own names, song titles…)

def fm(skill):
    t = (ROOT / 'skills' / skill / 'SKILL.md').read_text()
    m = re.match(r'---\n(.*?)\n---', t, re.S)
    d = dict(re.findall(r'^(\w+):\s*(.*)$', m.group(1), re.M)) if m else {}
    return d

def main(check_only):
    errs = []
    meta = json.loads((ROOT / 'skills.json').read_text())
    names = sorted(p.name for p in (ROOT / 'skills').iterdir() if p.is_dir())
    readme = (ROOT / 'README.md').read_text()
    for n in names:
        if not (ROOT / 'skills' / n / 'SKILL.md').exists(): errs.append(f'{n}: missing SKILL.md')
        elif fm(n).get('name') != n: errs.append(f'{n}: frontmatter name != folder name')
        if n not in meta: errs.append(f'{n}: add en/zh one-liners to skills.json')
        if not re.search(rf'^## {re.escape(n)}\s*$', readme, re.M): errs.append(f'{n}: add a "## {n}" section to README.md')
    for n in meta:
        if n not in names: errs.append(f'skills.json lists "{n}" but skills/{n}/ does not exist')
    if errs: return errs

    rows = ''.join(f"| [`{n}`](skills/{n}/) | {meta[n]['en']} / {meta[n]['zh']} |\n" for n in names)
    table = f'{BEGIN}\n| Skill | What it does |\n|---|---|\n{rows}{END}'
    if BEGIN in readme: new = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: table, readme, flags=re.S)
    else: errs.append('README.md is missing the SKILLS:BEGIN/END markers'); return errs
    mp = ROOT / '.claude-plugin' / 'marketplace.json'
    d = json.loads(mp.read_text())
    d['plugins'] = [{'name': n, 'description': f"{meta[n]['en']} {meta[n]['zh']}", 'source': './', 'strict': False,
                     'skills': [f'./skills/{n}']} for n in names]
    new_mp = json.dumps(d, ensure_ascii=False, indent=2) + '\n'
    if not check_only:
        (ROOT / 'README.md').write_text(new); mp.write_text(new_mp)
    elif new != readme or new_mp != mp.read_text():
        errs.append('README.md / marketplace.json out of date: run python3 scripts/sync.py')

    terms = [t.strip() for t in EXTRA.read_text().splitlines() if t.strip()] if EXTRA.exists() else []
    files = subprocess.run(['git', 'ls-files', '-co', '--exclude-standard'], cwd=ROOT, capture_output=True, text=True).stdout.split()
    for f in files:
        if f == 'scripts/sync.py': continue
        try: text = (ROOT / f).read_text()
        except (UnicodeDecodeError, IsADirectoryError, FileNotFoundError): continue
        for pat, why in PRIVATE:
            for m in re.finditer(pat, text):
                if f == 'LICENSE' or f.startswith('.claude-plugin'): continue
                errs.append(f'{f}: {why}: {m.group(0)[:50]}')
        for t in terms:
            if t in text: errs.append(f'{f}: contains forbidden term from .privacy-terms')
    return errs

if __name__ == '__main__':
    e = main('--check' in sys.argv)
    for x in e: print('✗', x)
    print('ok' if not e else f'{len(e)} problem(s)')
    sys.exit(1 if e else 0)
